In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('house-prices-advanced-regression-techniques/train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

Neural Networks can be very much applied to regression problem.<br>
In case of regression problem, use of softmax activation or any kind of activation is not required at the last layer.

### For predicting the selling price of the house:-
#### We will use neural network with 3 layers.
#### We will Use ‘ReLU’ as the activation function for the hidden layers because ReLU is linear function and its  value is max(0,x).
#### We can use 'Mean squared Error' as a loss function. (Instead of Cross-entropy Error.)
#### We will define the output layer with only one node to predict the House selling price. (Unlike 10 output layers in Apparel dataset.)
#### We will Use Linear activation function like ReLU for the output layer as we want ouput as a linear prediction value based on the model.

#### <u>Structure:</u>
    -- Remove Nan Values from data set and Columns that contain Nan Values.
    -- For categorical attributes, One hot Encode data. i.e. for n categories in column make n rows with in exactly 1 category. 
    1)1 input layer with input units equal to the number of features in dataset used to predict house price + 1 (for the bias unit).
    2)1 hidden layer - Keeping it simple. Assuming we don’t have complex data.
    3)Output layer with 1 unit giving us the prediction sale price.<br>
    4)Use Quadratic loss function to predict how well the neural network is performing. 
        L(w)=∑i(h(xi,w)−yi)^2
    5)Use Gradient Descent to minimize error and change weights.